
import { CertificateData } from '../types';

// Mock Certificate Database
export const CERTIFICATES: CertificateData[] = [
  { certId: 'TN/MAA/070/LTIEC0022', studentName: 'MONISHA M', courseName: 'WEB DEVELOPMENT', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CHE/071/LTIEC0023', studentName: 'CHANDRALEKHA G K', courseName: 'NXcad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0024', studentName: 'NAVANEETHA KRISHNAN', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/ERD/080/LTIEC0025', studentName: 'JAIRASWANTH', courseName: 'C,C++', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0026', studentName: 'ABHI NIVESH P', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0027', studentName: 'KELVIN A', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0028', studentName: 'J AMAL ZICO', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0029', studentName: 'BALAJI', courseName: 'WEB DEVELOPMENT', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0030', studentName: 'VASANTH', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0031', studentName: 'VISHNU KUMAR V', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0032', studentName: 'Dharsan V', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0033', studentName: 'PRABHU', courseName: 'autocad', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0034', studentName: 'ARUL LAKSHMI', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0035', studentName: 'Ganesh Pradeep V', courseName: 'Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0036', studentName: 'Rajapandi', courseName: 'C,C++', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0037', studentName: 'Theenarasu S', courseName: 'Master Diploma', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0038', studentName: 'Vijay M', courseName: 'Hypermesh', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0039', studentName: 'Keerthana', courseName: 'Sketchup', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0040', studentName: 'Nijandhan K', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0041', studentName: 'Surya M', courseName: 'Nxcad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0042', studentName: 'Lokkesh V', courseName: 'Master Diploma', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0043', studentName: 'Muthulingam K', courseName: 'Autocad,Solidworks,Creo,Nxcad', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0044', studentName: 'Palanisamy C', courseName: 'Master Diploma', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0045', studentName: 'Sathyaseelan', courseName: 'Ecad', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0046', studentName: 'Dayanathi S', courseName: 'Revit', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0047', studentName: 'Lithin ABINAV M R', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0048', studentName: 'Alagappan V', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0049', studentName: 'Varun Kumar C', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0050', studentName: 'Harsh B', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0051', studentName: 'Niresh C', courseName: 'Master Diploma', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0052', studentName: 'Lokesh K', courseName: 'Nxcad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0053', studentName: 'Sanjay Karthikeyan M', courseName: 'C,C++,Python,Java', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0054', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0055', studentName: 'Lokendra', courseName: 'Autocad,Catia,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0056', studentName: 'Narayana Prakash', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0057', studentName: 'Franklin Blesson', courseName: 'Nxcad,Nxcam', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0058', studentName: 'Nithyanandhan', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0059', studentName: 'Subramaniya Bharathi', courseName: 'Autocad', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0060', studentName: 'Dhanabal', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0061', studentName: 'Dharun Kumar', courseName: 'Full Stack', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0062', studentName: 'Booshan Bharatvaj', courseName: 'Full Stack', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0063', studentName: 'Haripriya', courseName: 'Creo,Wiring Harness', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0064', studentName: 'Karthikeyan', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0065', studentName: 'Anadha Ganapathy', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0066', studentName: 'Nandhini', courseName: 'Data Analytics', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0067', studentName: 'Manikandan', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0068', studentName: 'Karthikeyan', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0069', studentName: 'Amurthavarsini', courseName: 'Ecad,PLC,Scada', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0070', studentName: 'Kumar', courseName: 'Autocad,Solidworks,Ansys', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0071', studentName: 'Subhash Chandra Bose', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0072', studentName: 'Hem Advai', courseName: 'Autocad,Solidworks,Ansys', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0073', studentName: 'Ruthresh', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0074', studentName: 'Krishna Kumar Chandran', courseName: 'Ansys', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0075', studentName: 'Syed Sharukh', courseName: 'Autocad,Revit,Sketchup', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0076', studentName: 'Jairaswanth Loganathan', courseName: 'Python', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0077', studentName: 'Sanjay Balaji', courseName: 'Python', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0078', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0079', studentName: 'Jayachandran', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0080', studentName: 'Thennavan', courseName: 'Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0081', studentName: 'Albert Enstien', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0082', studentName: 'Sethupathi', courseName: 'Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0083', studentName: 'Anish Joseph', courseName: 'Autocad,Sketchup', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0084', studentName: 'Viswamani', courseName: 'Python', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0085', studentName: 'RINESH', courseName: 'Autocad', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0086', studentName: 'KAUSHIK', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0087', studentName: 'M K SREEJESH', courseName: 'Software Testing', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0088', studentName: 'V ARON', courseName: 'Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0089', studentName: 'S D MOHAN KARTHICK', courseName: 'Solidworks,ANSYS', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0090', studentName: 'R GOPINATH', courseName: 'Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0091', studentName: 'BOOBALA KRISHNAN J', courseName: 'CIVILCAD', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0092', studentName: 'SAGAYA AMBROSE S', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0093', studentName: 'Pranav A', courseName: 'Autocad', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0094', studentName: 'Rajavel', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0095', studentName: 'SANTHOSH', courseName: 'DATA ANALYTICS', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0096', studentName: 'Kishore sp', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0097', studentName: 'Dinesh kumar s', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0098', studentName: 'SIVA BALAMURUGAN P P', courseName: 'NXCAD', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0099', studentName: 'Naveen k', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0100', studentName: 'Ram prakash', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0101', studentName: 'Ashwin c', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0102', studentName: 'Nikesh S', courseName: 'Autocad,Solidworks,Creo,Catia', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0103', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0104', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0105', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0106', studentName: 'MONIKA S', courseName: 'python', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0107', studentName: 'SWATHI M', courseName: 'python', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0108', studentName: 'SHAMLI SAMPORNA S', courseName: 'python', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0109', studentName: 'SUVATHI P', courseName: 'SOFTWARE TESTING', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0110', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0111', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0112', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0113', studentName: '', courseName: '', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0114', studentName: 'MUKESH', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0115', studentName: 'PRAKASH', courseName: 'Solidworks', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0116', studentName: 'SURYA', courseName: 'Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0117', studentName: 'karthikeyan', courseName: 'Autocad,Solidworks,Creo', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0118', studentName: 'Bretto sam', courseName: 'Autocad,Solidworks,Creo,Catia', duration: '6 Months', completionDate: '', status: 'Completed' },
  { certId: 'TN/CBE/069/LTIEC0119', studentName: 'lavanya', courseName: 'python, java', duration: '6 Months', completionDate: '', status: 'Completed' },
];
