
import { CourseSummary } from '../types';

export const COURSE_SUMMARIES: CourseSummary[] = [
  {
    id: 'mech1',
    title: 'Precision Mechanical CAD Course – Mastering AutoCAD & SolidWorks',
    slug: "precision-mechanical-cad",
    category: 'Mechanical',
    oldPrice: '₹12,000',
    price: '₹6,499',
    duration: '1.5 – 2 Months',
    image: '/img/mech/autocad.webp',
    description: 'Master the art of mechanical design with our industry-leading AutoCAD and SolidWorks course.',
    modules: ['AutoCAD 2D/3D', 'SolidWorks Basics', 'Part Modeling', 'Assembly Design']
  },
  {
    id: 'mech2',
    title: 'SolidWorks Design Course (Mechanical Engineering)',
    slug: "solidworks-design",
    category: 'Mechanical',
    oldPrice: '₹25,000',
    price: '₹14,999',
    duration: '1.5 – 3 Months',
    image: '/img/mech/solidworks-408z.webp',
    description: 'Master SolidWorks and accelerate your career growth with expert-led training.',
    modules: ['Advanced Part Modeling', 'Surface Design', 'Sheet Metal', 'Weldments']
  },
  {
    id: 'mech3',
    title: 'Creo Parametric Course (Mechanical Engineering)',
    slug: "creo-parametric",
    category: 'Mechanical',
    oldPrice: '₹25,000',
    price: '₹14,999',
    duration: '1.5 – 3 Months',
    image: '/img/mech/creo-688z.webp',
    description: 'Master Creo Parametric and accelerate your career growth with expert-led training.',
    modules: ['Sketcher & Part Modeling', 'Assembly Design', 'Sheet Metal Design', 'Mechanism Design']
  },
  {
    id: 'mech4',
    title: 'CATIA V5 Course (Mechanical Engineering)',
    slug: "catia-v5",
    category: 'Mechanical',
    oldPrice: '₹30,000',
    price: '₹17,999',
    duration: '1.5 – 3 Months',
    image: '/img/mech/catia-118z.webp',
    description: 'Master CATIA V5 and accelerate your career growth with expert-led training.',
    modules: ['Sketcher & Part Design', 'Generative Shape Design', 'Assembly Design', 'Drafting']
  },
  {
    id: 'mech5',
    title: 'ANSYS Simulation Course (Mechanical Engineering)',
    slug: "ansys-simulation",
    category: 'Mechanical',
    oldPrice: '₹30,000',
    price: '₹17,999',
    duration: '2 – 3 Months',
    image: '/img/mech/ansys-670z.webp',
    description: 'Master ANSYS Simulation and accelerate your career growth with expert-led training.',
    modules: ['FEA Fundamentals', 'Static Structural Analysis', 'Modal & Thermal Analysis', 'Meshing Techniques']
  },
  {
    id: 'mech6',
    title: 'HyperMesh Course (Mechanical Engineering)',
    slug: "hypermesh",
    category: 'Mechanical',
    oldPrice: '₹40,000',
    price: '₹19,999',
    duration: '1.5 – 3 Months',
    image: '/img/mech/hypermesh-631z.webp',
    description: 'Master HyperMesh and accelerate your career growth with expert-led training.',
    modules: ['Geometry Cleanups', '2D & 3D Meshing', '1D Element Creation', 'Analysis Setup']
  },
  {
    id: 'mech7',
    title: 'ANSA Pre-Processing Course (Mechanical Engineering)',
    slug: "ansa-pre-processing",
    category: 'Mechanical',
    oldPrice: '₹25,000',
    price: '₹14,999',
    duration: '1.5 – 3 Months',
    image: '/img/mech/ansa-062z.webp',
    description: 'Master ANSA Pre-Processing and accelerate your career growth with expert-led training.',
    modules: ['Geometry Management', 'Shell & Solid Meshing', 'Batch Meshing', 'Model Completion']
  },
  {
    id: 'mech8',
    title: 'Computational Fluid Dynamics (CFD)',
    slug: "computational-fluid-dynamics",
    category: 'Mechanical',
    oldPrice: '₹25,000',
    price: '₹11,999',
    duration: '2 – 3 Months',
    image: '/img/mech/cfd-486z.webp',
    description: 'Master Computational Fluid Dynamics (CFD) and accelerate your career growth with expert-led training.',
    modules: ['Fluid Mechanics Basics', 'CFD Simulation Workflow', 'Turbulence Modeling', 'Post-processing Results']
  },
  {
    id: 'mech9',
    title: 'NX CAD (Unigraphics) Course (Mechanical Engineering)',
    slug: "nx-cad-unigraphics",
    category: 'Mechanical',
    oldPrice: '₹30,000',
    price: '₹17,999',
    duration: '2 – 3 Months',
    image: '/img/mech/nxcad-582z.webp',
    description: 'Master NX CAD (Unigraphics) and accelerate your career growth with expert-led training.',
    modules: ['Master Sketcher', 'Synchronous Modeling', 'Assembly & Drafting', 'Industrial Projects']
  },
  {
    id: 'mech10',
    title: 'Autodesk Inventor Course (Mechanical Engineering)',
    slug: "autodesk-inventor",
    category: 'Mechanical',
    oldPrice: '₹30,000',
    price: '₹17,999',
    duration: '1.5 – 3 Months',
    image: '/img/mech/autodesk-inventor-783z.webp',
    description: 'Master Autodesk Inventor and accelerate your career growth with expert-led training.',
    modules: ['Parametric Modeling', 'Adaptive Design', 'Simulation & Stress Analysis', 'Documentation']
  },
  {
    id: 'mech11',
    title: 'Wiring Harness Design Course',
    slug: "wiring-harness-design",
    category: 'Mechanical',
    oldPrice: '₹35,000',
    price: '₹19,999',
    duration: '1.5 – 2 Months',
    image: '/img/mech/wiring-harness-catia-256z.webp',
    description: 'Master Wiring Harness Design and accelerate your career growth with expert-led training.',
    modules: ['Electrical Fundamentals', 'CATIA V5 Electrical Library', 'Harness Routing', 'Formboard Design']
  },
  {
    id: 'mech12',
    title: '3D Printing & Prototyping',
    slug: "3d-printing-prototyping",
    category: 'Mechanical',
    oldPrice: '₹25,000',
    price: '₹14,999',
    duration: '1 – 1.5 Months',
    image: '/img/mech/3d-399z.webp',
    description: 'Master 3D Printing & Prototyping and accelerate your career growth with expert-led training.',
    modules: ['Types of 3D Printing', 'Slicing & STL Preparation', 'Machine Operation', 'Post-processing']
  },
  {
    id: 'it1',
    title: 'Full Stack Development Course – Build Complete Web Applications',
    slug: "full-stack-development",
    category: 'IT',
    oldPrice: '₹60,000',
    price: '₹34,999',
    duration: "4 – 6 Months",
    image: '/img/it/full-stack-development-171z.webp',
    description: 'Master Front-End, Back-End, Databases, and Deployment with React & Node.js.',
    modules: ['HTML5 & CSS3', 'Modern JavaScript (ES6+)', 'React.js Frontend', 'Node.js & MongoDB']
  },
  {
    id: 'it2',
    title: 'Web Development Course – Become a Full Stack Developer',
    slug: "web-development",
    category: 'IT',
    oldPrice: '₹34,999',
    price: '₹13,999',
    duration: "3 – 4 Months",
    image: '/img/it/web-development-387z.webp',
    description: 'Our Web Development Course is designed to help you become a professional Full Stack Web Developer. Learn to design, develop, and deploy modern websites.',
    modules: ['Web Fundamentals', 'Responsive Design', 'Frontend Frameworks', 'API Integration']
  },
  {
    id: 'it3',
    title: 'Software Testing Course – Become a QA Expert',
    slug: "software-testing",
    category: 'IT',
    oldPrice: '₹34,999',
    price: '₹13,999',
    duration: "3 – 4 Months",
    image: '/img/it/st-291z.webp',
    description: 'Master Manual and Automation Testing (Selenium) with real-time projects and placement support.',
    modules: ['SDLC & STLC', 'Manual Testing', 'Selenium Automation', 'API Testing (Postman)']
  },
  {
    id: 'it4',
    title: 'Data Analytics Course – Turn Data into Powerful Insights',
    slug: "data-analytics",
    category: 'IT',
    oldPrice: '₹29,999',
    price: '₹10,999',
    duration: "3 to 4 Months",
    image: '/img/it/da-013z.webp',
    description: 'Learn to collect, analyze, interpret, and visualize data using industry-standard tools like Excel, SQL, Power BI, and Python.',
    modules: ['Advanced Excel', 'SQL for Data Science', 'Power BI Dashboards', 'Python for Analytics']
  },
  {
    id: 'it5',
    title: 'Java Programming Course | Beginner to Advanced Training',
    slug: "java-programming",
    category: 'IT',
    oldPrice: '₹29,999',
    price: '₹11,999',
    duration: "210 Hours",
    image: '/img/it/java-747z.webp',
    description: 'Build a strong career in software development with our comprehensive Java Programming Course. Learn from basics to advanced Core Java with practical training and projects.',
    modules: ['Core Java Fundamentals', 'OOPs Concepts', 'Collections Framework', 'JDBC & MySQL']
  },
  {
    id: 'it6',
    title: 'Python Programming | Beginner to Advanced Training',
    slug: "python-programming",
    category: 'IT',
    oldPrice: '₹27,999',
    price: '₹10,999',
    duration: "180 Hours",
    image: '/img/it/python-267z.webp',
    description: 'Learn Python Programming from basics to advanced with practical training, real-time projects, and placement assistance.',
    modules: ['Python Syntax', 'Data Structures', 'File Handling', 'Libraries (NumPy, Pandas)']
  },
  {
    id: 'it7',
    title: 'Digital Marketing (Adv) | Master Digital Marketing Excellence',
    slug: "digital-marketing-adv",
    category: 'IT',
    oldPrice: '₹29,999',
    price: '₹10,999',
    duration: "210 Hours",
    image: '/img/it/digital-marketing-875z.webp',
    description: 'Master SEO, SEM, and Social Media Marketing strategies to grow brands and increase sales.',
    modules: ['SEO Optimization', 'Google Ads (SEM)', 'Social Media Strategy', 'Email Marketing']
  },
  {
    id: 'it8',
    title: 'UI/UX Design Course – Master Digital Product Design',
    slug: "ui-ux-design",
    category: 'IT',
    oldPrice: '₹34,999',
    price: '₹13,999',
    duration: "2 – 3 Months",
    image: '/img/it/ui-514z.webp',
    description: 'Master UI/UX Design from research to prototype with practical training and real-time projects.',
    modules: ['Design Thinking', 'Wireframing', 'Figma Mastery', 'Prototyping']
  },
  {
    id: 'civil1',
    title: 'Civil CAD',
    slug: "civil-cad",
    category: 'Civil',
    oldPrice: '₹10,000',
    price: '₹6,499',
    duration: '1.5 to 2 Months',
    image: '/img/civil/civil-cad.webp',
    description: 'Master Civil CAD and accelerate your career growth with expert-led training.',
    modules: ['AutoCAD Civil basic', 'Floor Plan Design', 'Elevation & Sections', 'Surveying Data']
  },
  {
    id: 'civil2',
    title: 'Revit Architecture',
    slug: "revit-architecture",
    category: 'Civil',
    oldPrice: '₹25,000',
    price: '₹14,999',
    duration: '1.5 to 2 Months',
    image: '/img/civil/revit-471z.webp',
    description: 'Master Revit Architecture and accelerate your career growth with expert-led training.',
    modules: ['BIM Concepts', 'Wall & Floor Creation', 'Family Creation', 'Rendering']
  },
  {
    id: 'civil3',
    title: 'SketchUp for Civil Engineering',
    slug: "sketchup",
    category: 'Civil',
    oldPrice: '₹25,000',
    price: '₹14,999',
    duration: '1 to 1.5 Months',
    image: '/img/civil/sketchup-430z.webp',
    description: 'Master SketchUp and accelerate your career growth with expert-led training.',
    modules: ['3D Modeling Basics', 'V-Ray Rendering', 'Interior Design', 'Outdoor Landscape']
  },
  {
    id: 'civil4',
    title: 'STAAD.Pro',
    slug: "staad-pro",
    category: 'Civil',
    oldPrice: '₹30,000',
    price: '₹17,999',
    duration: '2 to 3 Months',
    image: '/img/civil/staadpro-216z.webp',
    description: 'Master STAAD.Pro and accelerate your career growth with expert-led training.',
    modules: ['Structural Analysis', 'Concrete Design', 'Steel Design', 'Seismic Analysis']
  },
  {
    id: 'civil5',
    title: 'BIM Professional',
    slug: "bim-professional",
    category: 'Civil',
    oldPrice: '₹50,000',
    price: '₹34,999',
    duration: '2 to 3 Months',
    image: '/img/civil/bim-240z.webp',
    description: 'Master Building Information Modeling (BIM) and accelerate your career growth with expert-led training.',
    modules: ['BIM Implementation', 'Coordination (Navisworks)', 'LOD Standards', 'BIM Project execution']
  },
  {
    id: 'arts1',
    title: 'Graphic Design',
    slug: 'graphic-design',
    category: 'Arts',
    oldPrice: '₹18,000',
    price: '₹9,999',
    duration: '1.5 – 2 Months',
    image: '/img/arts/digital-marketing-840z.webp',
    description: 'Master Graphic Design using Photoshop, Illustrator and CorelDRAW.',
    modules: ['Adobe Photoshop', 'Adobe Illustrator', 'CorelDRAW Basics', 'Logo Design']
  },
  {
    id: 'arts2',
    title: 'Video Editing',
    slug: 'video-editing',
    category: 'Arts',
    oldPrice: '₹18,000',
    price: '₹9,999',
    duration: '1.5 – 2 Months',
    image: '/img/arts/ms-office-specialist-640z.webp',
    description: 'Master Video Editing with Premiere Pro and After Effects.',
    modules: ['Adobe Premiere Pro', 'After Effects Motion Graphics', 'Color Grading', 'Sound Editing']
  },
  {
    id: 'arts3',
    title: 'Digital Marketing (Media)',
    slug: "digital-marketing-media",
    category: 'Arts',
    oldPrice: '₹29,999',
    price: '₹11,999',
    duration: '90 Days',
    image: '/img/arts/digital-marketing-840z.webp',
    description: 'Focus on branding, content strategy and online presence.',
    modules: ['Content Marketing', 'Social Media Branding', 'Influencer Marketing', 'Analytics']
  },
  {
    id: 'arts4',
    title: 'MS Office',
    slug: "ms-office",
    category: 'Arts',
    oldPrice: '₹12,000',
    price: '₹5,999',
    duration: '1 to 1.5 Months',
    image: '/img/arts/ms-office-specialist-640z.webp',
    description: 'Master MS Office and build essential computer skills for academic and professional success.',
    modules: ['Advanced Excel', 'Word for professional documents', 'PowerPoint presentations', 'Outlook Basics']
  },
  {
    id: 'arts5',
    title: 'Tally with GST',
    slug: "tally-with-gst",
    category: 'Arts',
    oldPrice: '₹15,000',
    price: '₹5,999',
    duration: '1.5 to 2 Months',
    image: '/img/arts/tally-with-gst-448z.webp',
    description: 'Master Tally with GST and accelerate your career growth with expert-led training.',
    modules: ['Accounting Vouchers', 'Inventory Management', 'GST Reports', 'Tally Prime Features']
  },
  {
    id: 'kid1',
    title: 'Robotics for Kids',
    slug: "robotics-for-kids",
    category: 'Kids',
    price: '₹1',
    duration: '1 to 2 Months',
    image: 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?auto=format&fit=crop&q=80&w=600',
    description: 'Fun robotics program for kids to learn coding, electronics, and build real robots!',
    modules: ['Intro to Electronics', 'Arduino for Kids', 'Robot Building', 'Block-based Coding']
  },
  {
    id: 'kid2',
    title: 'Scratch Coding',
    slug: "scratch-coding",
    category: 'Kids',
    price: 'Starts @ ₹4,000',
    duration: '1 Month',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=600',
    description: 'Learn coding through fun games and animations using block-based programming!',
    modules: ['Sprite Controls', 'Loops & Conditions', 'Game Development', 'Creative Storytelling']
  }
];
